### ISSUE TITLE
/signup post returns Cannot find module '@architect/functions'

### ISSUE THREAD

**Issue by misterjuicebox** [architect-examples/arc-example-notes#2]
I creating my own unique S3 bucket names. Ran npx create and npx deploy, then visited the staging link provided. When I try to signup with an email and password I get a page with only

Cannot find module '@architect/functions'

Help?

https://pgjvajhwx4.execute-api.us-west-1.amazonaws.com/staging/

**Comment by brianleroux** [comment]
hmmm, can you link your source ?

**Comment by misterjuicebox** [comment]
It's also not adding a person to the db when I call:

 data.people.put(person)

The example code didn't add a hashed pw to the table in the .arc file so I tried just passing an email in for a person, since my table didn't have a column for pw, but that didn't work either...

**Comment by brianleroux** [comment]
eh sorry about this experience! I should disable issue trackers in here / just forgot about this thread and only seeing it again today. =( if you need any help lmk! the architect slack is a good real time channel
